### ISSUE TITLE
Model files could not access

### ISSUE THREAD

**Issue by fengxiaZhou** [Adrian-Cantu/PhANNs#12]
Hi, 
 the model files could not download by https://edwards.sdsu.edu/phanns/download/model.tar, the location seems to not be an active website?

**Comment by Adrian-Cantu** [comment]
Hi, 

The website changed a few month ago and it seems that I failed to update the documentation, please try [https://phanns.com/download/model.tar](https://phanns.com/download/model.tar)

Regards,
Adrian

**Comment by fengxiaZhou** [comment]
Hi Adrian,


 Thank very much for your quick reply. The model file was downloaded successfully according the new location.


 Sincerely,


Fengxia






| |
fengxiazhou_hit
|
|
***@***.***
|
---- Replied Message ----
| From | Adrian ***@***.***> |
| Date | 11/18/2022 01:33 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [Adrian-Cantu/PhANNs] Model files could not access (Issue #12) |

Hi,

The website changed a few month ago and it seems that I failed to update the documentation, please try https://phanns.com/download/model.tar

Regards,
Adrian
