### ISSUE TITLE
How long does it take to the server to make predictions?

### ISSUE THREAD

**Issue by loukesio** [Adrian-Cantu/PhANNs#3]
Dear Adrian, 

Thank you for the PhANNs it seems great. I am currently trying to use PhANNs. I uploaded two fasta files.
One file with 150 translated ORFs and one with 3 translated ORF sequences a week ago. I have not seen a feedback in my bookmarked page. I know that there is an option to run PhANNs through terminal but is there a way 
to check how long it takes for online server to make predictions.

its not really an issue but a question

Thank you for your time

Update: Today I can not even access the bookmarked files. 502 Bad Gateway. I hope you are doing fine. I am not sure if this 
page is maintained

**Comment by Adrian-Cantu** [comment]
Hi, 

Congratulations, you found a new bug and broke the server's back end!! When a protein's length is exactly 2 a division by 0 happens.  I took the site down to fix it. It should be online in a few hours. The prediction should only take a few minutes. I will post an update when the site is online again.

Thanks a lot for using PhANNs!!

**Comment by loukesio** [comment]
Dear Adrian, 

You are welcome. Sorry the fuss. I am looking forward to submit again my ORFs. Thank you

**Comment by Adrian-Cantu** [comment]
Hi, 
Don't worry about that, I'm actually happy you are using PhANNs and finding bugs. The site is now up and running. Your fasta file had some small sequences (2 or 3 aminoacids) that were causing a division by zero. Those sequences now flagged as not valid and the error page directs you to a new submission form that removes invalid sequences.

Please resubmit your files and let me know if it is working

**Comment by loukesio** [comment]
Dear Adrian, 

Thank you for fixing the bug. I already got the first results. I am looking forward to summarise them
Have a nice day
